[build]
builder = "NIXPACKS"
buildCommand = "if [ \"$IS_CLIENT\" = 'true' ]; then npm install && npm run build; else npm install --omit=dev; fi"

[deploy]
startCommand = "if [ \"$IS_CLIENT\" = 'true' ]; then npx serve -s client/dist; else npx prisma generate --schema=server/prisma/schema.prisma && npx prisma migrate deploy --schema=server/prisma/schema.prisma && node server/src/index.js; fi"
